### ISSUE TITLE
Dataset Numbers Explaination ?

### ISSUE THREAD

**Issue by Sandbird** [RubixML/Divorce#1]
What do they numbers in the dataset stand for ? It's 0 to 4. Is that the 'likeliness' from Negative to most Positive ? It's weird that they are from 0 to 4. Never seen anything similar i mean.

**Comment by andrewdalpino** [comment]
Hi @Sandbird thanks for your question

The numbers in the dataset stand for the values of the features on a common scale used in questionnaires called the [Likert Scale](https://en.wikipedia.org/wiki/Likert_scale)

> The format of a typical five-level Likert item, for example, could be:
> 1. Strongly disagree
> 2. Disagree
> 3. Neither agree nor disagree
> 4. Agree
> 5. Strongly agree

The questions themselves can be found in the [features.txt](https://github.com/RubixML/Divorce/blob/master/features.txt) file in the project root

Computers typically start count at 0 which is why it's 0 to 4 (instead of 1 to 5) but any arbitrary interval over the natural numbers would work (ex. 4001 to 4005)  

I'll be happy to answer any followup questions

**Comment by Sandbird** [comment]
Thanks Andrew, I wasn't sure if that was the case. I was searching for a '5' inside the dataset thinking of the same thing, but finding none made me doubt it. :)
